# Site settings
title: Morf-Jekyll
email:
author:
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

facebook-username:
twitter-username:
instagram-username:
dribbble-username:
tumlbr-username:
medium-username:
github-username:


# Build settings
markdown: kramdown

# Exclude for gulp / browsersync
exclude: [node_modules, gulpfile.js]

#CSS Libraries
tachyons: true
bass-css: false
foundation: false

#If you have your custom css files / libraries from CDN add the links here:
# for example: https://unpkg.com/tachyons@4.4.1/css/tachyons.min.css
custom-cdn-css-1:
custom-cdn-css-1:
